# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=1023, verbose_name='Descripción')),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
        ),
    ]
